[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION",
  "CXXFLAGS=-std=c++20 -fconcepts -fPIC",
  "CFLAGS=-std=c11 -fPIC",
]

# [target.aarch64-unknown-linux-gnu.env]
# CXXFLAGS = "-std=c++20 -fconcepts -fPIC"
# CFLAGS = "-std=c11 -fPIC"
